#@TYPE: Machine
#@NAME: NETFIELD PHYBOARD POLLUX iMX8M PLUS
#@DESCRIPTION:
#@PARTNUMBERS:
#@MAINTAINER: Hilscher Gesellschaft fuer Systemautomation mbH
#@TEMPLATECONF: meta-hilscher-netfield-phytec/conf/samples

# specify system device of the target platform, this is required e.g. for the recovery process (deploy target)
PHYSICAL_SYSTEM_DEVICE ?= "/dev/mmcblk1"

#-------------------------------------------------------------------------------
require conf/machine/include/phyboard-pollux-imx8mp-3.conf
SOC_FAMILY .= ":netfield-phyboard-pollux-imx8mplus"

#-------------------------------------------------------------------------------
PRECONFIGURED_SYSTEM_CONNECTIONS ?= "eth0 eth1"

MACHINE_FEATURES += "pci wifi 3g hab"

# No cifx connected via SPI
CIFX_SPI_CONFIGS = ""

MACHINE_ESSENTIAL_EXTRA_RRECOMMENDS:append = " kernel-module-netanalyzer libnetana netanalyzer-firmware netanalyzer-bsl"
MACHINE_ESSENTIAL_EXTRA_RRECOMMENDS:append = " uionetx"
# For overlays
MACHINE_ESSENTIAL_EXTRA_RDEPENDS:append = " device-tree"
# To allow updating special eMMC boot partition
# MACHINE_ESSENTIAL_EXTRA_RDEPENDS:append = " mmc-utils"
# To be able to use Intel WiFi / BT card
# MACHINE_ESSENTIAL_EXTRA_RRECOMMENDS:append = " linux-firmware-iwlwifi-misc linux-firmware-ibt"
# KERNEL_FEATURES:append:pn-linux-imx = " features/iwlwifi/iwlwifi.scc"
# KERNEL_FEATURES:append:pn-linux-fslc-imx = " features/iwlwifi/iwlwifi.scc"

# Add support for Realtek WiFi cards
# MACHINE_ESSENTIAL_EXTRA_RRECOMMENDS:append = " linux-firmware-rtl8168 linux-firmware-rtl8192cu linux-firmware-rtl8192su"
# KERNEL_FEATURES:append:pn-linux-imx = " features/wifi/realtek-usb.cfg"
# KERNEL_FEATURES:append:pn-linux-fslc-imx = " features/wifi/realtek-usb.cfg"

# Don't install some recommended packages, into rescue image
BAD_RECOMMENDATIONS:pn-hilscher-rescue-image += " \
    linux-firmware-iwlwifi-misc linux-firmware-ibt \
    linux-firmware-rtl8168 linux-firmware-rtl8192cu linux-firmware-rtl8192su \
    kernel-module-netanalyzer libnetana netanalyzer-firmware netanalyzer-bsl \
    kernel-module-uio-netx \
    kernel-5.4* \
"

SWU_FILES += "${IMX_BOOT_FILE};boot1.bin"
SWU_FILE_ATTRIBUTES += "boot1.bin;path=\"/dev/mmcblk1\";offset=\"${IMX_BOOT_SEEK}K\";name=\"boot.bin\";version;install-if-different=true"

OEM_BRANDING_IMAGES = "hilscher-netfield-image-oem-netfield"
