#@TYPE: Machine
#@NAME: NETFIELD PHYBOARD POLLUX iMX8M PLUS
#@DESCRIPTION:
#@PARTNUMBERS:
#@MAINTAINER: Hilscher Gesellschaft fuer Systemautomation mbH
#@TEMPLATECONF: meta-hilscher-netfield-phytec/conf/samples

# specify system device of the target platform, this is required e.g. for the recovery process (deploy target)
PHYSICAL_SYSTEM_DEVICE ?= "/dev/mmcblk1"

#-------------------------------------------------------------------------------
require conf/machine/phyboard-pollux-imx8mp-3.conf
MACHINEOVERRIDES =. "phyboard-pollux-imx8mp-3:"
KERNEL_DEVICETREE = "freescale/imx8mp-phyboard-pollux-rdk.dtb"

BOOTLOADER_SEEK:${MACHINE} = "32"
#-------------------------------------------------------------------------------
require include/phytec_common.inc

PRECONFIGURED_SYSTEM_CONNECTIONS ?= "eth0 eth1"

MACHINE_FEATURES += "pci wifi 3g hab"

# No cifx connected via SPI
CIFX_SPI_CONFIGS = ""

MACHINE_ESSENTIAL_EXTRA_RRECOMMENDS:append = " kernel-module-netanalyzer libnetana netanalyzer-firmware netanalyzer-bsl"
MACHINE_ESSENTIAL_EXTRA_RRECOMMENDS:append = " uionetx"


# Don't install some recommended packages, into rescue image
BAD_RECOMMENDATIONS:pn-hilscher-rescue-image += " \
    kernel-module-netanalyzer libnetana netanalyzer-firmware netanalyzer-bsl \
    kernel-module-uio-netx \
    kernel-5.15* \
"

SWU_FILES += "${IMAGE_BOOTLOADER};boot.bin"
SWU_FILE_ATTRIBUTES += "boot.bin;path=\"/dev/mmcblk0\";offset=\"${BOOTLOADER_SEEK}K\";name=\"boot.bin\";version;install-if-different=true"

# UBOOT_ENTRYPOINT:mx8m-generic-bsp = "0x40800000"
UBOOT_ENTRYPOINT:mx8m-generic-bsp = "0x50800000"
# UBOOT_LOADADDRESS:mx8m-generic-bsp = "0x58000000"
