#!/bin/sh

platform_init_enabled() {
	return 0
}

create_gpio() {
	gpiobank=$1;
	gpionum=$2;
	dir=$3;
	name=$4;
	label="";

	case "$gpiobank" in
	1) label="30200000.gpio" ;;
	2) label="30210000.gpio" ;;
	3) label="30220000.gpio" ;;
	4) label="30230000.gpio" ;;
	5) label="30240000.gpio" ;;
	esac

	if [ -z "$label" ]; then
		__msg "Unknown GPIO bank $gpiobank passed, unable to create GPIO"
	else
		gpioindex=-1

		for chip in /sys/class/gpio/gpiochip*; do
			if grep -q "$label" "$chip/label"; then
				gpiobase=$(cat "$chip/base")
				gpioindex=$((gpiobase+gpionum))
				break
			fi
		done

		if [ $gpioindex -eq -1 ]; then
			__msg "Unable to find GPIO $gpiobank:$gpionum"
		else
			echo "$gpioindex" > /sys/class/gpio/export
			echo "$dir" > /sys/class/gpio/gpio${gpioindex}/direction
			ln -s /sys/class/gpio/gpio${gpioindex}/value  "/var/platform/$name"
		fi
	fi
}

platform_init_run() {
	# We need the pub key loader to access the certificate
	load_kernel_module pub-key-loader

	__debug "Loading platform devices / drivers ..."

	__debug "Creating platform symlinks ..."

	# USB 3.0
	create_gpio 1 13 "in"   "in_usb3_phy0_nfault"

	# M2
	create_gpio 1 11 "high" "out_m.2_boot"
	create_gpio 2 8  "in" "in_m.2_sync0"
	create_gpio 2 9  "in" "in_m.2_sync1"

	# ETH0 with TSN
	create_gpio 1 7  "in" "in_eth0_syncclk"

	# DIP switches
	create_gpio 5 9 "in" "in_dip_in1"
	create_gpio 5 7 "in" "in_dip_in2"
	create_gpio 5 8 "in" "in_dip_in3"
	create_gpio 5 6 "in" "in_dip_in4"

	# Digital Inputs
	create_gpio 5 26 "in" "in_din1"
	create_gpio 5 27 "in" "in_din2"
	create_gpio 5 28 "in" "in_din3"
	create_gpio 5 29 "in" "in_din4"

	# Digital Outputs
	create_gpio 5 4  "in"  "in_ndout1_st"
	create_gpio 4 27 "low" "out_dout1"
	create_gpio 5 3  "in"  "in_ndout2_st"
	create_gpio 4 24 "low" "out_dout2"
	create_gpio 4 29 "in"  "in_ndout3_st"
	create_gpio 4 26 "low" "out_dout3"
	create_gpio 4 30 "in"  "in_ndout4_st"
	create_gpio 4 21 "low" "out_dout4"

	# UART mux pin
	create_gpio 1 10 "high" "sel_uart2_rs485_nrs232"
	
	# LEDs
	ln -s /sys/class/leds/usr1_green/brightness /var/platform/led_usr1_green
	ln -s /sys/class/leds/usr1_yellow/brightness /var/platform/led_usr1_yellow
	ln -s /sys/class/leds/usr2_green/brightness /var/platform/led_usr2_green
	ln -s /sys/class/leds/usr2_yellow/brightness /var/platform/led_usr2_yellow
}
