#!/bin/sh

platform_init_enabled() {
	return 0
}

# create_gpio() {
# 	gpio=$1; dir=$2; name=$3

# 	echo "$gpio" > /sys/class/gpio/export
# 	echo "$dir" > /sys/class/gpio/gpio${gpio}/direction

# 	ln -s /sys/class/gpio/gpio${gpio}/value  "/var/platform/$name"
# }

# load_overlay() {
# 	mkdir -p "/sys/kernel/config/device-tree/overlays/$1"
# 	cat "/boot/dt-overlays/$1.dtbo" > "/sys/kernel/config/device-tree/overlays/$1/dtbo"
# }

# read_slot() {
# 	slot=$1
# 	pin0=$(( slot * 3 ))
# 	pin1=$(( slot * 3 + 1 ))
# 	pin2=$(( slot * 3 + 2 ))

# 	if [ ! -e /sys/devices/platform/soc@0/soc@0:bus@30800000/30a50000.i2c/i2c-3/3-0022 ]; then
# 		# This should never happen, but somehow pca device is not available
# 		__msg "Unable to find pca gpio expander, which should be available on this board"
# 		echo 0
# 		return
# 	fi

# 	# Get gpio base from pca expander
# 	expander_base=$(ls /sys/devices/platform/soc@0/soc@0:bus@30800000/30a50000.i2c/i2c-3/3-0022/gpio/ | sed 's/[^0-9]*//g')

# 	# Read gpio's from expander
# 	create_gpio $(( expander_base + pin0 )) "in" "id_slot${slot}_bit0"
# 	create_gpio $(( expander_base + pin1 )) "in" "id_slot${slot}_bit1"
# 	create_gpio $(( expander_base + pin2 )) "in" "id_slot${slot}_bit2"
# 	bit0=$(cat "/var/platform/id_slot${slot}_bit0")
# 	bit1=$(cat "/var/platform/id_slot${slot}_bit1")
# 	bit2=$(cat "/var/platform/id_slot${slot}_bit2")
# 	id=$(( bit0 +  bit1 * 2 + bit2 * 4 ))

# 	echo $id
# }

# detect_plugged_modules() {
# 	# Slot 0/1 can contain same modules
# 	for slot in 0 1; do
# 		slotid=$(read_slot $slot)
# 		case $slotid in
# 			0) __msg "Slot${slot}: unpopulated"
# 			    ;;
# 			2) __msg "Slot${slot}: RS485"
# 			   load_overlay "imx8gate-ied-slot${slot}-rs232"
# 			   ;;
# 			3) __msg "Slot${slot}: TPM"
# 			   load_overlay "imx8gate-ied-slot${slot}-tpm"
# 			   ;;
# 			4) __msg "Slot${slot}: CAN"
# 			   load_overlay "imx8gate-ied-slot${slot}-can"
# 			   ;;
# 			5) __msg "Slot${slot}: CL420"
# 			   load_overlay "imx8gate-ied-slot${slot}-cl420"
# 			   ;;
# 			6) __msg "Slot${slot}: RS232"
# 			   load_overlay "imx8gate-ied-slot${slot}-rs232"
# 			   ;;
# 			*) __msg "Slot${slot}: UNKNOWN <$slotid>"
# 			   ;;
# 		esac
# 	done

# 	# Slot 2
# 	slotid=$(read_slot 2)
# 	case $slotid in
# 		0) __msg "Slot2: unpopulated"
# 		   ;;
# 		1) __msg "Slot2: DI4O4"
# 		   # 64 is base of gpiochip2
# 		   create_gpio $(( 64 + 0 )) "in" "ied-di4o4_i0"
# 		   create_gpio $(( 64 + 1 )) "in" "ied-di4o4_i1"
# 		   create_gpio $(( 64 + 6 )) "in" "ied-di4o4_i2"
# 		   create_gpio $(( 64 + 7 )) "in" "ied-di4o4_i3"
# 		   create_gpio $(( 64 + 8 )) "low" "ied-di4o4_o0"
# 		   create_gpio $(( 64 + 9 )) "low" "ied-di4o4_o1"

# 		   # Get gpio base from pca expander
# 		   expander_base=$(ls /sys/devices/platform/soc@0/soc@0:bus@30800000/30a50000.i2c/i2c-3/3-0022/gpio/ | sed 's/[^0-9]*//g')

# 		   create_gpio $(( expander_base + 9 ))  "low" "ied-di4o4_o2"
# 		   create_gpio $(( expander_base + 10 )) "low" "ied-di4o4_o3"
# 		   ;;
# 		*) __msg "Slot2: UNKNOWN <$slotid>"
# 		   ;;
# 	esac
# }

platform_init_run() {
	# Allow loading dtb overlays
	mount -t configfs none /sys/kernel/config

	# __debug "Exporting the platform leds ..."
	# for led in edge_green edge_yellow; do
	# 	ln -s /sys/class/leds/${led}/brightness /var/platform/led_${led}
	# done
}
