#!/bin/bash

####################################################################################
# NOTE: This is a wrapper of the original uboot-mkimage tool, to be able to use    #
#       the standard yocto kernel-fitimage.bbclass and it's call of uboot-mkimage. #
####################################################################################

# Depending on the key type we may need to inject a parameter and remove the
# local key reference. In case of pkcs11 we will setup UBOOT_MKIMAGE_PARAMS.
while (( "$#" )); do
	if [ -v UBOOT_MKIMAGE_PARAMS ] && [ -n "${UBOOT_MKIMAGE_PARAMS}" ]; then
		# remove the parameter '-k [path to local key]'
		# and append custom parameter setup ($UBOOT_MKIMAGE_PARAMS)
		[ "$1" = "-k" ] && shift && shift && params+=(${UBOOT_MKIMAGE_PARAMS}) && continue
	fi
	params+=("${1}")
	shift
done

$(dirname $(realpath $0))/uboot-mkimage.bin "${params[@]}"
